sudo: required
language: go

go:
  - 1.8.x

services:
  - docker
  - mongodb

before_install:
  - docker pull alpine:edge

before_script:
  - sleep 10
  - mongo --version
  - >-
    mongo test --eval 'db.test.insert({item: "item", val: "test" });'

script:
  - make travis
  - sleep 10
  - curl http://localhost:8090/version
  - docker logs mgob
