sudo: required
language: go

go:
  - 1.8.x

services:
  - docker
  - mongodb

before_install:
  - docker run -dp 9000:9000 -e "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE" -e "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" minio/minio server /export
  - sudo curl -o /usr/bin/mc https://dl.minio.io/client/mc/release/linux-amd64/mc
  - chmod u+x /usr/bin/mc
  - docker run -dp 20022:22 atmoz/sftp:alpine test:test:::backup

before_script:
  - sleep 10
  - >-
    mongo test --eval 'db.test.insert({item: "item", val: "test" });'
  - mc config host add local http://127.0.0.1:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY S3v4
  - mc mb local/backup

script:
  - make travis
  - sleep 60
  - docker logs mgob
  - curl http://localhost:8090/version
  - docker logs mgob 2>&1 | grep finished

after_success:
  - make publish

deploy:
  provider: script
  script: make release
  on:
    tags: true
    branch: master