sudo: required
language: go

go:
  - 1.8.x

services:
  - docker
  - mongodb

before_install:
  - docker pull alpine:edge

before_script:
  - sleep 10
  - >-
    mongo test --eval 'db.test.insert({item: "item", val: "test" });'
  - >-
    mongo test --eval 'db.runCommand({whatsmyuri : 1});'

script:
  - make travis
  - sleep 60
  - curl http://localhost:8090/version
  - docker logs mgob 2>&1 | grep finished
